class  Addflight  {
  constructor(
    FID,
    AID,
    DEPARTUREPLACE,
    DEPATUREDATE,
    DEPARTURETIME,
    ARRIVALPLACE,
    ARRIVALDATE,
    ARRIVALTIME,
    DURATION,
    NOOFSEATS,
    PRICEPERPERSON,

  ) {
    this.FID = FID;
    this.AID =  AID;
    this.DEPARTUREPLACE = DEPARTUREPLACE;
    this.DEPATUREDATE = DEPATUREDATE;
    this.DEPARTURETIME = DEPARTURETIME;
    this.ARRIVALPLACE = ARRIVALPLACE;
    this.ARRIVALDATE = ARRIVALDATE ;
    this.ARRIVALTIME = ARRIVALTIME ;
    this.DURATION =DURATION ;
    this.NOOFSEATS = NOOFSEATS ;
    this.PRICEPERPERSON = PRICEPERPERSON ;
  }
}

 